### ISSUE TITLE
Investigate NewsKit WordPress theme 

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#787]
# Purpose of the spike
A large number of applications in News are rendered with WordPress (non-headless), we would like to investigate building a WordPress theme/integration that can make use of what we've currently built with NewsKit. 

# Outcomes of the Spike

- What can we do with NewsKit and WordPress? can we use our theme export, can we use any of our components (likely not all of them as WordPress will render with PHP) but stuff that always requires JS e.g. modal could be useful still, would be good to get a definition of where this seam lies.    
- [Guttenberg](https://wordpress.org/gutenberg/) integration is this somewhere where NewsKit can add value?
- Ideally a simple demo of what this would look like, I'm sure there are 100's of tutorials to build a WordPress Theme follow one and consider how we can do a NewsKit one.   
- Identify the next steps

# Time box
5 days

# Supporting Information

https://codex.wordpress.org/Theme_Development

**Comment by messmike** [comment]
fyi Dario Minigo (designer on the Times) who works on Money Mentor mentioned that this could be useful to them, as MM uses Wordpress. Developers work in WordPress and make custom blocks. There is currently talk of Money Mentor moving to NewsKit in the future, but nothing has been confirmed yet - this could be something that they could pick up if they can use the NK theme.

**Comment by mutebg** [comment]
## Theme.json

- Tokens and global styles can be defined in theme.json ( colors, space, shadows, font sizes and font families ).
    - We can extract our newskit tokens and add them to that theme.json file
    - We can re-define default elements and block styles in theme.json file so that they look similar to newskit
- Tokens are exposed to wordpress admin so that users can use them in the editor
- Tokens are exposed as css variables so devs can use them.
- It works for WP version 6+ and for bellow with gutenburg plugin
- there is possibility to create multiple theme.json files in the same theme so that you have different variations ( like dark and light theme )


## Plugin with React

- wordpress uses PHP, so it can not render components on the server
- In order render react you need to create WP plugin. React is used as external script ( same way you might use any other JS library as jqiuery for example ). The mechanism is very similar to what we do with “island architecture”, we render an empty html element using PHP and later when JS kicks in use React.render to host “islands” inside the empty html element.

## Notes

- in NewsUK, we use wordpress mainly as headless CMS, so front-end rendering is handled by title teams. In that regard, having theme.json and plugins inside wp-admin is not very useful.

## Demo

[https://github.com/newscorp-ghfb/newskit-wordpress-experiment](https://github.com/newscorp-ghfb/newskit-wordpress-experiment)
