### ISSUE TITLE
Figma Libraries v5 not aligned to specs of v4

### ISSUE THREAD

**Issue by dj-kmuldoon** [newscorp-ghfb/NewsKit#828]
Dow Jones sees style definitions in v5 Figma Libraries created by NewsKit are not 1:1 with the definitions created in the v4 Figma Libraries.

Dow Jones is interested in upgrading to the new v5 for Figma and React components, but these non-alignments represent a need for a full audit and regression testing cycle to ensure brand expectations in v4 are 100% met in v5. 

A few examples can explain the situation.

-  In v5 Dow Jones Figma library, the font 'editorialDisplay010' has a line spacing of 112.5% where v4 had 64px. If the percentage matched the visual, this would be a non-issue but v4 is more tightly spaced than the new v5 definition. Difficult to believe this definition was changed by designers in the v4 version while v5 was being stood up by NewsKit.
- FNL Palette colors Secondary500 and Secondary600 are identical values in v5, which does not align with v4

**Comment by LukeFinch** [comment]
Hi Kevin, We've created these against a snapshot in time, so there may be some divergence from what you have today, and also potential errors that could have been introduced with our limited team taking on the effort of producing a theme in the v5 format for everyone across NewsCorp. 

The expectation is that teams will manage and publish these themes themselves going forward. 

Ideally, this would be done through the Tokens Studio plugin - so that changes are synced across design and code.

We'll look to onboard you and the DowJones team on how to carry out this process so you can get the themes aligned with your expectations.

**Comment by jps** [comment]
@dj-kmuldoon @LukeFinch do we feel this issue is still needed? if so how can we progress it?

**Comment by dj-kmuldoon** [comment]
@jps I'm not certain TBH. If Dow Jones wants to upgrade to the v5, we'll need to do a full audit. So far, no pressing need.
