### ISSUE TITLE
Investigate REM support 

### ISSUE THREAD

**Issue by jps** [newscorp-ghfb/NewsKit#851]
# Purpose of the spike

Previously there were technical limitations related to font cropping that prevented us from moving to REM however since the solution was reworked and migrated to font metrics these are no more 🥇 .

At present the base NewsKit theme uses px-based sizing for fonts. Many teams across News (The Sun, The Times) use REM-based values for their fonts. There is no limitation in them moving their own themes to use REM but... there is no guarantee that all NewsKit components will render as expected as their layout will potentially be adjusted by different font sizes.

Also it's worth calling out that just because teams are using REM it doesn't mean that they are doing it correctly.

![Image](https://user-images.githubusercontent.com/350953/234908224-8953d1b7-cae4-46ae-98ff-65d342cee3f3.png)

![Image](https://user-images.githubusercontent.com/350953/234908377-9c7d7f44-a28b-435b-8d82-65593fa6ec64.png)

![image](https://user-images.githubusercontent.com/350953/235710365-d3fe1ebd-f345-4af0-bb67-64ccd52d4923.png)

However, some sites appear to do a good job up to a certain point, this example of the BBC is at 32px, it breaks beyond this. 

![image](https://user-images.githubusercontent.com/350953/235711338-03e9027d-0224-4f23-bb1d-4c1d77256898.png)

The purpose of this spike is to conduct an audit and assess what changes will need to be made to move to REM in the base theme. 

- Update the base font sizes to be REM-based values, and look at each in the theme checker at different user-defined font sizes (24px,32px) to look for abnormalities. We suspect things like TextField, Button, Button could all cause issues due to the fact they will be different sizes
- Do we want to set any other values to be REM or EM based. 
- Do we want to consider moving to REM on the site first, the site looked quite broken at larger user-defined font sizes, what work will be required to rectify this?

# Outcomes of the Spike

- Feedback learnings to the team 
- An idea of the amount of work required to do this

# Time box
4 days

# Supporting Information

This article is worth a read https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/

Geri's Pixels vs REMs research: https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/4380098683/PX+vs+REMS

**Comment by JohnTParsons** [comment]
WHAT HAS BEEN DONE & WHY?

There are two ways of adding rem support to newskit:
- the data-driven approach: theme is converted from pixels to rems in Figma and then exported as a new version using Publisher.
- the code-driven approach (this one): use a flag to convert pixels to rems when createTheme/compileTheme functions are called, as part of the application startup. For the spike, I've implemented this approach in case we want to be cautious provides brands with a way to turn rem support on/off easily, in case of issues found later on. If we used this approach in the real solution, it would only add a fraction of a second to the startup time (especially now that we cache compiled themes in memory).

To prove that is dynamically configurable per theme, you will see that only the light and brand them have the 'useRem' flag set to true. If you switch the site or Storybook to the dark theme, you will see the screen switch back to pixels.

**Comment by JohnTParsons** [comment]
HOW DOES SITE & STORYBOOK APPEAR WITH
REMS + 24PX FONT SIZE?

To test this, go to chrome://settings/fonts in Chrome and check that
"Font size" is showing 24px.

The site is still usable. The header buttons have fixed width, so the "Search" and "View Github" text is slightly cropped.

Storybook looks fine with the exception of:

Toast - not enough room for 4-column "Toast api examples" so that single row wraps onto second line (with two buttons on it) with no row gap

**Comment by JohnTParsons** [comment]
HOW DOES SITE & STORYBOOK APPEAR WITH
REMS + 32PX FONT SIZE?

To test this, go to chrome://settings/fonts in Chrome and check that
"Font size" is showing 32px.

The site is still usable. The header buttons have fixed width, so the "Search" and "View Github" text is even more cropped than at 24px.

All Storybook components seem to display okay with the exception of:

Byline - multiple bylines spaced too close

Grid-layout - rows too close?

Icon-button - all stories hardcoded to 32px by 32px

modal-layouts-only - title "account" is cropped as content is bottom-justified. Is that correct?

Pagination
- All the non-dark themes are displaying in Storybook in REM mode as expected, with the exception of The Sun theme ONLY, which displays larger text (but not as large as other themes), however the pagination arrows are still small.
- Input And Description story has custom input component that is too narrow due to custom styles fixed to pixels. (The Sun theme does not have that issue.)

Switch - overlap on stories that try to fit in 6 columns

Toast - not enough room for 4-column "Toast api examples" so that single row wraps onto second line (with two buttons on it) with no row gap

toast-e2e - no gaps between rows on the Default story

Tooltip - not enough blank space left for the Default/Placements stories to show the tooltips in the expected placement. Not a big issue?

Tooltip e2e - not enough blank space left for the story to show the tooltips in the expected placement.

typography - not enough for 2-column stories, such as "crop vs no crop"

Video Player - the title and description stays in a small font

**Comment by JohnTParsons** [comment]
WHAT TICKETS NEED CREATING ON THE BACK OF THIS SPIKE?

Maybe a ticket to add the REM Storybook Addon (https://storybook.js.org/addons/storybook-addon-rem) as this would speed up and standardise the technique for REM testing across all browsers.

What needs changing to make the docs site look better? Not much? Just making the header buttons have rem-based widths?

What needs changing to make Storybook look better at 32px? Fewer stories fixed to 3 and 4 columns, but probably not worth the effort.

What needs changing to make Storybook components look better? Not sure. All the actual components look okay to me but could do with more eyes on it to check for breaking component layouts.

**Comment by jps** [comment]
Thanks for this @JohnTParsons looks less broken than I thought it would. 


## Site issues

by no means exhaustive as I haven't looked at every page but a few things that could be improved if we did decide to move forward with this. 

At 32px the home page looks pretty broken in the REM mode, as does the top nav.
![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/f5e39310-7f1f-4ac9-abcb-5604c2986373)

The sidebar on the components section is a bit broken 

![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/b507fc98-de7f-40ed-aae8-df2b3fd133c1)

In the about section, I can't get to the top

![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/60994f45-1801-4231-93ca-fac09b1b025b)

The code view doesn't look to be scaling 

![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/e4065b02-4a8b-437b-b1c7-16fe7e11e91c)


The long tokens in this table make it feel a bit broken 

![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/418eb9ff-9015-4b3a-af42-30dc511ce12c)


## storybook issues

only a couple I've noticed

block in theme checker looks broken
![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/60458d35-9c6b-4c2b-91f7-7d56a9f3bb90)

switch component looks broken 
![image](https://github.com/newscorp-ghfb/NewsKit/assets/350953/18e2eee2-433e-4eb3-969f-b3d4992f55f0)


A few thoughts 💭  

The approach you've taken is interesting but I do fear that it's an additional layer of complexity that isn't needed given users can do this via the theme system anyway? 

I see we have moved the spacing and sizing system to be REM based, if this was something we wanted to pursue, we would need to rewrite both pages of documentation in the theming section. I wonder if it would make sense to prioritise fronts and then consider if we want to tackle spacing and sizing later, we would need to test this half way solution. 

There are fundamental questions for designers that come out of moving to REM-based sizing, in that sized components will now behave differently, i.e. a 32px heigh button is now many different sizes. I kinda see an advantage of having both as REM based but it may be a different mode for designers to operate in especially when considering responsive design.

**Comment by lhaggar** [comment]
Closing due to layout issues etc.
